import inspect
from enum import Enum
from uuid import uuid4


class HttpStatusCode(int, Enum):
    """HTTP status codes for AppError exceptions."""

    BAD_REQUEST = 400
    UNAUTHORIZED = 401
    FORBIDDEN = 403
    NOT_FOUND = 404
    CONFLICT = 409
    INTERNAL_SERVER_ERROR = 500


class AppErrorCode(str, Enum):
    """Error codes for AppError exceptions."""

    # Authentication & Authorization
    E_BAD_TOKEN = "E_BAD_TOKEN"
    E_NOT_WHITELISTED = "E_NOT_WHITELISTED"
    E_SESSION_FORBIDDEN = "E_SESSION_FORBIDDEN"
    E_PARTICIPANT_FORBIDDEN = "E_PARTICIPANT_FORBIDDEN"

    # Resource Not Found
    E_SESSION_NOT_FOUND = "E_SESSION_NOT_FOUND"
    E_CHANNEL_NOT_FOUND = "E_CHANNEL_NOT_FOUND"
    E_NO_LIVE_URL = "E_NO_LIVE_URL"
    E_NO_VOD_URL = "E_NO_VOD_URL"
    E_NO_PLAYBACK_ID = "E_NO_PLAYBACK_ID"
    E_NO_PUBLIC_PLAYBACK_ID = "E_NO_PUBLIC_PLAYBACK_ID"

    # Session State & Lifecycle
    E_SESSION_EXISTS = "E_SESSION_EXISTS"
    E_SESSION_TERMINATED = "E_SESSION_TERMINATED"
    E_SESSION_NOT_STARTED = "E_SESSION_NOT_STARTED"
    E_SESSION_CREATE_FAILED = "E_SESSION_CREATE_FAILED"
    E_SESSION_END_FAILED = "E_SESSION_END_FAILED"
    E_SESSION_VERSION_CONFLICT = "E_SESSION_VERSION_CONFLICT"

    # Room Management
    E_ROOM_CREATE_FAILED = "E_ROOM_CREATE_FAILED"
    E_ROOM_DELETE_FAILED = "E_ROOM_DELETE_FAILED"
    E_ROOM_METADATA_UPDATE_FAILED = "E_ROOM_METADATA_UPDATE_FAILED"
    E_ROOM_CAPACITY = "E_ROOM_CAPACITY"
    E_NAME_CONFLICT = "E_NAME_CONFLICT"

    # LiveKit & Streaming
    E_LIVE_STREAM_IN_PROGRESS = "E_LIVE_STREAM_IN_PROGRESS"
    E_LIVE_STREAM_START_FAILED = "E_LIVE_STREAM_START_FAILED"
    E_LIVE_STREAM_END_FAILED = "E_LIVE_STREAM_END_FAILED"
    E_TOKEN_GENERATION_FAILED = "E_TOKEN_GENERATION_FAILED"
    E_LIVEKIT_NOT_CONFIGURED = "E_LIVEKIT_NOT_CONFIGURED"
    E_PARTICIPANT_UPDATE_FAILED = "E_PARTICIPANT_UPDATE_FAILED"

    # LiveKit Twirp Errors
    E_LIVEKIT_CANCELED = "E_LIVEKIT_CANCELED"
    E_LIVEKIT_UNKNOWN = "E_LIVEKIT_UNKNOWN"
    E_LIVEKIT_INVALID_ARGUMENT = "E_LIVEKIT_INVALID_ARGUMENT"
    E_LIVEKIT_MALFORMED = "E_LIVEKIT_MALFORMED"
    E_LIVEKIT_DEADLINE_EXCEEDED = "E_LIVEKIT_DEADLINE_EXCEEDED"
    E_LIVEKIT_NOT_FOUND = "E_LIVEKIT_NOT_FOUND"
    E_LIVEKIT_BAD_ROUTE = "E_LIVEKIT_BAD_ROUTE"
    E_LIVEKIT_ALREADY_EXISTS = "E_LIVEKIT_ALREADY_EXISTS"
    E_LIVEKIT_PERMISSION_DENIED = "E_LIVEKIT_PERMISSION_DENIED"
    E_LIVEKIT_UNAUTHENTICATED = "E_LIVEKIT_UNAUTHENTICATED"
    E_LIVEKIT_RESOURCE_EXHAUSTED = "E_LIVEKIT_RESOURCE_EXHAUSTED"
    E_LIVEKIT_FAILED_PRECONDITION = "E_LIVEKIT_FAILED_PRECONDITION"
    E_LIVEKIT_ABORTED = "E_LIVEKIT_ABORTED"
    E_LIVEKIT_OUT_OF_RANGE = "E_LIVEKIT_OUT_OF_RANGE"
    E_LIVEKIT_UNIMPLEMENTED = "E_LIVEKIT_UNIMPLEMENTED"
    E_LIVEKIT_INTERNAL = "E_LIVEKIT_INTERNAL"
    E_LIVEKIT_UNAVAILABLE = "E_LIVEKIT_UNAVAILABLE"
    E_LIVEKIT_DATA_LOSS = "E_LIVEKIT_DATA_LOSS"

    # Captions & Transcripts
    E_TRANSCRIPT_QUERY_FAILED = "E_TRANSCRIPT_QUERY_FAILED"
    E_CAPTION_GENERATION_FAILED = "E_CAPTION_GENERATION_FAILED"
    E_UNSUPPORTED_STT_CONFIG = "E_UNSUPPORTED_STT_CONFIG"
    E_PLAYLIST_GENERATION_FAILED = "E_PLAYLIST_GENERATION_FAILED"
    E_SEGMENT_GENERATION_FAILED = "E_SEGMENT_GENERATION_FAILED"
    E_MASTER_PLAYLIST_GENERATION_FAILED = "E_MASTER_PLAYLIST_GENERATION_FAILED"
    E_CAPTION_ENABLE_FAILED = "E_CAPTION_ENABLE_FAILED"
    E_CAPTION_DISABLE_FAILED = "E_CAPTION_DISABLE_FAILED"
    E_CAPTION_STATUS_FAILED = "E_CAPTION_STATUS_FAILED"
    E_PARTICIPANT_LANGUAGE_UPDATE_FAILED = "E_PARTICIPANT_LANGUAGE_UPDATE_FAILED"

    # Webhooks
    E_WEBHOOK_INVALID_JSON = "E_WEBHOOK_INVALID_JSON"
    E_WEBHOOK_MISSING_EVENT_TYPE = "E_WEBHOOK_MISSING_EVENT_TYPE"
    E_WEBHOOK_VALIDATION_ERROR = "E_WEBHOOK_VALIDATION_ERROR"
    E_WEBHOOK_ERROR = "E_WEBHOOK_ERROR"
    E_WEBHOOK_CONFIG_MISSING = "E_WEBHOOK_CONFIG_MISSING"
    E_WEBHOOK_INVALID_SIGNATURE = "E_WEBHOOK_INVALID_SIGNATURE"
    E_WEBHOOK_SIGNATURE_ERROR = "E_WEBHOOK_SIGNATURE_ERROR"

    # External Services
    E_EXTERNAL_LIVE_ERROR = "E_EXTERNAL_LIVE_ERROR"

    # Configuration
    E_CONFIG_MISSING = "E_CONFIG_MISSING"

    # Generic/Validation
    E_INVALID_REQUEST = "E_INVALID_REQUEST"
    E_INTERNAL_ERROR = "E_INTERNAL_ERROR"

    def __str__(self) -> str:
        return self.value


class AppError(Exception):
    def __init__(
        self,
        errcode: AppErrorCode,
        errmesg: str,
        status_code: HttpStatusCode = HttpStatusCode.INTERNAL_SERVER_ERROR,
    ):
        self.errcode = errcode.value
        self.errmesg = errmesg
        self.status_code = status_code.value

        # Capture caller info at raise site
        caller_frame = inspect.stack()[1]
        module = inspect.getmodule(caller_frame.frame)
        module_name = (
            module.__name__
            if module and getattr(module, "__name__", None)
            else caller_frame.filename
        )
        self.caller_info = f"{module_name}:{caller_frame.function}:{caller_frame.lineno}"
        self.erresid = uuid4().hex[:10]

        super().__init__(f"{self.errcode}: {errmesg}")
